# Embeds migrations/*.sql into a generated header used by storage/migrations.cpp.
# Expects: MIGRATIONS_DIR (input directory), OUT_FILE (header to generate).
cmake_minimum_required(VERSION 3.20)

file(GLOB _migration_files "${MIGRATIONS_DIR}/*.sql")
list(SORT _migration_files)

set(_header
"// Generated by cmake/EmbedMigrations.cmake from migrations/*.sql. Do not edit.\n\
#pragma once\n\
#include <cstddef>\n\
\n\
namespace streamforge::migrations {\n\
\n\
struct EmbeddedMigration {\n\
    const char* name;\n\
    const char* sha256;   // checksum of the source SQL file, verified at apply time\n\
    const char* sql;\n\
};\n\
\n\
inline constexpr EmbeddedMigration kMigrations[] = {\n")

foreach(_file ${_migration_files})
    get_filename_component(_name "${_file}" NAME_WE)
    file(SHA256 "${_file}" _sha)
    file(READ "${_file}" _sql)
    string(FIND "${_sql}" ")SQL" _collision)
    if(NOT _collision EQUAL -1)
        message(FATAL_ERROR "Migration ${_name} contains the raw-string terminator ')SQL'")
    endif()
    string(APPEND _header "    {\"${_name}\", \"${_sha}\", R\"SQL(${_sql})SQL\"},\n")
endforeach()

string(APPEND _header
"};\n\
\n\
inline constexpr std::size_t kMigrationCount = sizeof(kMigrations) / sizeof(kMigrations[0]);\n\
\n\
}  // namespace streamforge::migrations\n")

file(WRITE "${OUT_FILE}" "${_header}")
message(STATUS "Embedded ${_migration_files} into ${OUT_FILE}")
